# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-31 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20190619_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascota',
            options={'permissions': set([('is_uno', 'Usuario Uno'), ('is_dos', 'Usuario Dos')])},
        ),
    ]
