# Generated by Django 2.2.4 on 2019-09-08 03:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados_Pedido',
            fields=[
                ('estado_pedido', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Guia_Pedido',
            fields=[
                ('checkpoint', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_novedad', models.DateField(default=datetime.datetime.now)),
                ('nota_pedido', models.CharField(default='N/A', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(default=datetime.datetime.now)),
                ('cantidad_requerida', models.IntegerField()),
                ('codigo_articulo_r', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_materiales.Articulo')),
                ('pedido_guia_r', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_pedido.Guia_Pedido')),
            ],
        ),
    ]
