# Generated by Django 2.2.5 on 2019-09-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0002_auto_20190907_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='existencias',
            field=models.IntegerField(default=0),
        ),
    ]
