# Generated by Django 2.2.4 on 2019-09-08 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('nombre_lote', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('detalle_lote', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Elemento',
            fields=[
                ('nombre_tipo_elemento', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('detalle_tipo_elemento', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Metrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metrica', models.CharField(max_length=50)),
                ('detalle_metrica', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('codigo_articulo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=50)),
                ('fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('ficha_tecnica', models.CharField(max_length=500)),
                ('valor', models.IntegerField()),
                ('lote_articulo_r', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_materiales.Lote')),
                ('tipo_elemento_r', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_materiales.Tipo_Elemento')),
                ('unidad_metrica_r', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_materiales.Unidad_Metrica')),
            ],
        ),
    ]
